spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: root  
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080   